name: Release

on: 
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Build
      run: |
        npm install
        npm run build

    - name: Test
      run: |
        npm run test:pixi5
        npm run test:pixi6
        npm run test:pixi7

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/browser/*.js
        token: ${{ secrets.PERSONAL_GITHUB_TOKEN }}
        draft: false

    - name: Publish
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      